doceasy:
  server:
    host: doceasy.local.test:8080
    address: http://${doceasy.server.host}
  identity:
    confirmation:
      token:
        lifetime: 1h
  account:
    password:
      minimum-length: 6

server:
  port: 8080
vaadin:
  urlMapping: /start/*

feign:
  client:
    config:
      default:
        loggerLevel: full

spring:
  data:
    mongodb:
      authentication-database: admin
      username: doceasy
      password: qweqwe123qwe
      database: doceasy
      port: 27017
      host: localhost

  mail:
    host: smtp.yandex.com
    port: 465
    username: no-reply@nomia.net
    password: RaBfNL2BsahH5yu
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: false
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    test-connection: true

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:54321/doceasy
    username: doceasy
    password: qweqwe123qwe
    driverClassName: org.postgresql.Driver

debug: true
logging.level.ru.d1g.doceasy.core.integration.ModuleClient: TRACE
